### ISSUE TITLE
Discord user: not connected

### ISSUE THREAD

**Issue by leandrodeassis** [TheMightyV/vita-presence-the-server#2]
I'm having this issue, the Discord ID is setting ok (The GUI version is working)

Discord ID: (hidden)
Discord user: not connected
PS Vita: connected to 192.168.1.23:51966
Playing: Trophy Collection (NPXS10008)

EDIT: Tested the win32 compiled and worked. Compiled from the source for my raspberry pi (64 bits SO) and nothing =(

![image](https://user-images.githubusercontent.com/889104/119067805-3ee1b600-b9b9-11eb-8561-aabeb39c0dd5.png)

**Comment by Nyabsi** [comment]
it is because you have installed discord via snap instead of using the debian package.

**Comment by LetGoMyLegos** [comment]
I'm having the same problem.
